[app]
# Interface and port where the app will run its webserver.  The default value
# of localhost will only listen to connections from the current machine. To
# listen on all interfaces use '0.0.0.0'. To listen on the default web address
# port, use port 80 (this will require running with elevated permissions).
address = "localhost:9000"

# Database.
[db]
host = "listmonk-db.c3c66we2cn2t.ap-south-1.rds.amazonaws.com"
port = 5432
user = "postgres"
password = "leanfolks1$"

# Ensure that this database has been created in Postgres.
database = "listmonk-db"

ssl_mode = "disable"
max_open = 25
max_idle = 25
max_lifetime = "300s"

# Optional space separated Postgres DSN params. eg: "application_name=listmonk gssencmode=disable"
params = ""
